server:
  http2:
    enabled: true
  port: 9153

api:
  prefix: /v1

spring:
    application:
        name: Split Bill
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    upload:
        directory: uploads
    datasource:
        url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/splitbill
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:password}
        hikari:
            pool-name: HikariConnection
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 2000000
            connection-timeout: 30000
    jpa:
      hibernate:
        ddl-auto: update
    security:
        jwt:
            secret-key: y/r4c6UVRXNxK0Hns0n6mMz+Ry7kgF2UXXGBoPNFWII=
            expiration-time: 3600000
            refresh-token:
                secret-key: 1+MYiAcCRQ5oJQvu562CifFqEph+QMlYyjK55q42azs=
                expiration-time: 3600000
    devtools:
      restart:
        enabled: true
      livereload:
        enabled: true
        actuator:
    endpoints:
      web:
        exposure:
          include: 'health,info,metrics,prometheus,env'

avatar:
  base-url: http://localhost:9153/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: WARN
    com.portofolio.splitbill: DEBUG
